### ISSUE TITLE
locked-in situation

### ISSUE THREAD

**Issue by square-root-1** [hobgoblina/oblique-strategies#4]
on my gigaset GS185, Android 8.1 smartphone, i cannot exit the app because the 3 navigation buttons below don't show up. These buttons are on the display (and not below the display) on this phone

**Comment by hobgoblina** [comment]
Thanks for making me aware of this!

Hopefully you can the navigation bar visible by swiping up from the bottom (or down from the top), but it may not work with your device/android version.

For the next version, I've added an "immersive mode" setting and set the default to false, making immersive mode an opt-in feature rather than a default as it is now. The new version should be available in a few days.

**Comment by square-root-1** [comment]
thanks for making the changes so quickly.
I also checked on an Huawei tablet: same behaviour.
Navigation buttons (triangle/circle/square) disappear and
cannot be swiped back. One has to press volume-up/down
to get out of this.

  17.02.2024 06:28, schrieb Lina²:

**Comment by hobgoblina** [comment]
good to know that there's some device/OS inconsistencies for that feature. I appreciate your testing it out!
